### ISSUE TITLE
Vault compatibility?

### ISSUE THREAD

**Issue by extendedclip** [PlaceholderAPI/MegaEconomy-Expansion#1]
Just wondering and correct me if I am wrong but wouldn't the Vault expansion make this obsolete? I am not familiar with the dependency "MegaEconomy" but I would assume as an economy plugin that it looks into Vault?

**Comment by LemmoTresto** [comment]
MegaEconomy has certain placeholders which many economy plugins don’t have. The plugin also has looked into Vault so don’t worry about that.

**Comment by extendedclip** [comment]
Ok cool I was just wondering. I do the same about every economy plugin when people ask why I don't make an expansion for it directly
